export const SET_POSTS = 'SET_POSTS'
export const LOADING_DATA = 'LOADING_DATA'
export const LOADING_UI = 'LOADING_UI'
export const LOADING_USER = 'LOADING_USER'
export const SET_USER = 'SET_USER'
export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'